version: "2"
services:
  samba:
    image: lordpedal/samba
    container_name: samba
    volumes:
      - 'path-to-dir-share:/lordpedal' #Ruta carpeta compartida
    ports:
      - "137:137" #Puerto protocolo NetBios
      - "138:138" #Puerto protocolo NetBios
      - "139:139" #Puerto protocolo SMB
      - "445:445" #Puerto protocolo SMB
    restart: always
